// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/ai-team" | "/calendar" | "/calendar/time-clock" | "/calendar/time-off" | "/calendar/timesheets" | "/credentials" | "/credentials/federal" | "/credentials/federal/[sourceId]" | "/credentials/local" | "/credentials/local/[sourceId]" | "/credentials/municipal" | "/credentials/municipal/[sourceId]" | "/credentials/other" | "/credentials/other/[sourceId]" | "/credentials/state" | "/credentials/state/[sourceId]" | "/dashboard" | "/dev-controls" | "/dev-controls/analytics" | "/dev-controls/deploy" | "/dev-controls/git" | "/dev-controls/logs" | "/dev-controls/releases" | "/dev-controls/security" | "/dev-controls/ssh" | "/development" | "/helpdesk" | "/helpdesk/canned-responses" | "/helpdesk/settings" | "/helpdesk/system-tickets" | "/helpdesk/system-tickets/[ticketId]" | "/helpdesk/system-tickets/new" | "/helpdesk/user-tickets" | "/helpdesk/user-tickets/[ticketId]" | "/login" | "/project-management" | "/servers" | "/servers/live" | "/servers/nextbidder" | "/servers/nextbidder/credentials" | "/servers/nexttask" | "/servers/nexttask/credentials" | "/servers/nexttech" | "/servers/nexttech/credentials" | "/servers/portals" | "/servers/portals/credentials" | "/servers/sources" | "/servers/sources/credentials" | "/servers/tradelines" | "/servers/tradelines/[tradeline]" | "/servers/tradelines/credentials" | "/session-logs" | "/settings" | "/settings/clients" | "/settings/clients/[id]" | "/settings/clients/new" | "/settings/profile" | "/settings/timesheets" | "/studio" | "/team" | "/team/members" | "/team/members/[id]" | "/team/members/new" | "/team/permissions" | "/team/reports" | "/team/roles" | "/the-forge" | "/tickets"
type AppRouteHandlerRoutes = "/ai-team/api/control" | "/ai-team/api/status" | "/ai-team/api/usage" | "/api/ai-extractions" | "/api/ai-extractions/by-project" | "/api/ai-extractions/clair" | "/api/ai-sessions" | "/api/ai-sessions/buckets" | "/api/clients" | "/api/clients/[id]" | "/api/clients/[id]/devs" | "/api/clients/[id]/projects" | "/api/deploy/dev-environment" | "/api/dev-controls/analytics/debug" | "/api/dev-controls/analytics/engine" | "/api/dev-redirect" | "/api/dev-server" | "/api/dev-session/connect" | "/api/dev-session/disconnect" | "/api/dev-session/status" | "/api/engine-redirect" | "/api/engine/health" | "/api/nextbidder/worker/health" | "/api/patcher/[...path]" | "/api/portals/worker/health" | "/api/server/[action]" | "/api/servers/health" | "/api/servers/logs" | "/api/servers/reboot" | "/api/sources/worker/health" | "/api/susan/[...path]" | "/api/susan/chat" | "/api/susan/conflicts" | "/api/susan/notifications" | "/api/team/members" | "/api/team/members/[id]" | "/api/team/members/[id]/deactivate" | "/api/team/permissions" | "/api/team/roles" | "/api/team/stats" | "/api/tradelines" | "/api/tradelines/[action]" | "/api/tradelines/[action]/[tradeline]" | "/api/tradelines/stats/[tradeline]" | "/api/tradelines/worker/health" | "/api/users" | "/project-management/api/clair/[...path]" | "/project-management/api/clients" | "/project-management/api/conventions" | "/project-management/api/conventions/[id]" | "/project-management/api/phases/[projectId]" | "/project-management/api/pipeline" | "/project-management/api/project-docs" | "/project-management/api/project-knowledge" | "/project-management/api/project-paths" | "/project-management/api/projects" | "/project-management/api/projects/[id]" | "/project-management/api/projects/summary" | "/the-forge/the-forge"
type PageRoutes = never
type LayoutRoutes = "/" | "/credentials"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/ai-team": {}
  "/ai-team/api/control": {}
  "/ai-team/api/status": {}
  "/ai-team/api/usage": {}
  "/api/ai-extractions": {}
  "/api/ai-extractions/by-project": {}
  "/api/ai-extractions/clair": {}
  "/api/ai-sessions": {}
  "/api/ai-sessions/buckets": {}
  "/api/clients": {}
  "/api/clients/[id]": { "id": string; }
  "/api/clients/[id]/devs": { "id": string; }
  "/api/clients/[id]/projects": { "id": string; }
  "/api/deploy/dev-environment": {}
  "/api/dev-controls/analytics/debug": {}
  "/api/dev-controls/analytics/engine": {}
  "/api/dev-redirect": {}
  "/api/dev-server": {}
  "/api/dev-session/connect": {}
  "/api/dev-session/disconnect": {}
  "/api/dev-session/status": {}
  "/api/engine-redirect": {}
  "/api/engine/health": {}
  "/api/nextbidder/worker/health": {}
  "/api/patcher/[...path]": { "path": string[]; }
  "/api/portals/worker/health": {}
  "/api/server/[action]": { "action": string; }
  "/api/servers/health": {}
  "/api/servers/logs": {}
  "/api/servers/reboot": {}
  "/api/sources/worker/health": {}
  "/api/susan/[...path]": { "path": string[]; }
  "/api/susan/chat": {}
  "/api/susan/conflicts": {}
  "/api/susan/notifications": {}
  "/api/team/members": {}
  "/api/team/members/[id]": { "id": string; }
  "/api/team/members/[id]/deactivate": { "id": string; }
  "/api/team/permissions": {}
  "/api/team/roles": {}
  "/api/team/stats": {}
  "/api/tradelines": {}
  "/api/tradelines/[action]": { "action": string; }
  "/api/tradelines/[action]/[tradeline]": { "action": string; "tradeline": string; }
  "/api/tradelines/stats/[tradeline]": { "tradeline": string; }
  "/api/tradelines/worker/health": {}
  "/api/users": {}
  "/calendar": {}
  "/calendar/time-clock": {}
  "/calendar/time-off": {}
  "/calendar/timesheets": {}
  "/credentials": {}
  "/credentials/federal": {}
  "/credentials/federal/[sourceId]": { "sourceId": string; }
  "/credentials/local": {}
  "/credentials/local/[sourceId]": { "sourceId": string; }
  "/credentials/municipal": {}
  "/credentials/municipal/[sourceId]": { "sourceId": string; }
  "/credentials/other": {}
  "/credentials/other/[sourceId]": { "sourceId": string; }
  "/credentials/state": {}
  "/credentials/state/[sourceId]": { "sourceId": string; }
  "/dashboard": {}
  "/dev-controls": {}
  "/dev-controls/analytics": {}
  "/dev-controls/deploy": {}
  "/dev-controls/git": {}
  "/dev-controls/logs": {}
  "/dev-controls/releases": {}
  "/dev-controls/security": {}
  "/dev-controls/ssh": {}
  "/development": {}
  "/helpdesk": {}
  "/helpdesk/canned-responses": {}
  "/helpdesk/settings": {}
  "/helpdesk/system-tickets": {}
  "/helpdesk/system-tickets/[ticketId]": { "ticketId": string; }
  "/helpdesk/system-tickets/new": {}
  "/helpdesk/user-tickets": {}
  "/helpdesk/user-tickets/[ticketId]": { "ticketId": string; }
  "/login": {}
  "/project-management": {}
  "/project-management/api/clair/[...path]": { "path": string[]; }
  "/project-management/api/clients": {}
  "/project-management/api/conventions": {}
  "/project-management/api/conventions/[id]": { "id": string; }
  "/project-management/api/phases/[projectId]": { "projectId": string; }
  "/project-management/api/pipeline": {}
  "/project-management/api/project-docs": {}
  "/project-management/api/project-knowledge": {}
  "/project-management/api/project-paths": {}
  "/project-management/api/projects": {}
  "/project-management/api/projects/[id]": { "id": string; }
  "/project-management/api/projects/summary": {}
  "/servers": {}
  "/servers/live": {}
  "/servers/nextbidder": {}
  "/servers/nextbidder/credentials": {}
  "/servers/nexttask": {}
  "/servers/nexttask/credentials": {}
  "/servers/nexttech": {}
  "/servers/nexttech/credentials": {}
  "/servers/portals": {}
  "/servers/portals/credentials": {}
  "/servers/sources": {}
  "/servers/sources/credentials": {}
  "/servers/tradelines": {}
  "/servers/tradelines/[tradeline]": { "tradeline": string; }
  "/servers/tradelines/credentials": {}
  "/session-logs": {}
  "/settings": {}
  "/settings/clients": {}
  "/settings/clients/[id]": { "id": string; }
  "/settings/clients/new": {}
  "/settings/profile": {}
  "/settings/timesheets": {}
  "/studio": {}
  "/team": {}
  "/team/members": {}
  "/team/members/[id]": { "id": string; }
  "/team/members/new": {}
  "/team/permissions": {}
  "/team/reports": {}
  "/team/roles": {}
  "/the-forge": {}
  "/the-forge/the-forge": {}
  "/tickets": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/credentials": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
