// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../src/app/ai-team/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/ai-team">> = Specific
  const handler = {} as typeof import("../../src/app/ai-team/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/calendar/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/calendar">> = Specific
  const handler = {} as typeof import("../../src/app/calendar/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/calendar/time-clock/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/calendar/time-clock">> = Specific
  const handler = {} as typeof import("../../src/app/calendar/time-clock/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/calendar/time-off/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/calendar/time-off">> = Specific
  const handler = {} as typeof import("../../src/app/calendar/time-off/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/calendar/timesheets/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/calendar/timesheets">> = Specific
  const handler = {} as typeof import("../../src/app/calendar/timesheets/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/credentials/federal/[sourceId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/credentials/federal/[sourceId]">> = Specific
  const handler = {} as typeof import("../../src/app/credentials/federal/[sourceId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/credentials/federal/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/credentials/federal">> = Specific
  const handler = {} as typeof import("../../src/app/credentials/federal/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/credentials/local/[sourceId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/credentials/local/[sourceId]">> = Specific
  const handler = {} as typeof import("../../src/app/credentials/local/[sourceId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/credentials/local/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/credentials/local">> = Specific
  const handler = {} as typeof import("../../src/app/credentials/local/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/credentials/municipal/[sourceId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/credentials/municipal/[sourceId]">> = Specific
  const handler = {} as typeof import("../../src/app/credentials/municipal/[sourceId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/credentials/municipal/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/credentials/municipal">> = Specific
  const handler = {} as typeof import("../../src/app/credentials/municipal/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/credentials/other/[sourceId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/credentials/other/[sourceId]">> = Specific
  const handler = {} as typeof import("../../src/app/credentials/other/[sourceId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/credentials/other/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/credentials/other">> = Specific
  const handler = {} as typeof import("../../src/app/credentials/other/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/credentials/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/credentials">> = Specific
  const handler = {} as typeof import("../../src/app/credentials/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/credentials/state/[sourceId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/credentials/state/[sourceId]">> = Specific
  const handler = {} as typeof import("../../src/app/credentials/state/[sourceId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/credentials/state/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/credentials/state">> = Specific
  const handler = {} as typeof import("../../src/app/credentials/state/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dev-controls/analytics/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dev-controls/analytics">> = Specific
  const handler = {} as typeof import("../../src/app/dev-controls/analytics/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dev-controls/deploy/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dev-controls/deploy">> = Specific
  const handler = {} as typeof import("../../src/app/dev-controls/deploy/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dev-controls/git/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dev-controls/git">> = Specific
  const handler = {} as typeof import("../../src/app/dev-controls/git/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dev-controls/logs/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dev-controls/logs">> = Specific
  const handler = {} as typeof import("../../src/app/dev-controls/logs/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dev-controls/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dev-controls">> = Specific
  const handler = {} as typeof import("../../src/app/dev-controls/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dev-controls/releases/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dev-controls/releases">> = Specific
  const handler = {} as typeof import("../../src/app/dev-controls/releases/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dev-controls/security/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dev-controls/security">> = Specific
  const handler = {} as typeof import("../../src/app/dev-controls/security/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dev-controls/ssh/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dev-controls/ssh">> = Specific
  const handler = {} as typeof import("../../src/app/dev-controls/ssh/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/development/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/development">> = Specific
  const handler = {} as typeof import("../../src/app/development/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/helpdesk/canned-responses/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/helpdesk/canned-responses">> = Specific
  const handler = {} as typeof import("../../src/app/helpdesk/canned-responses/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/helpdesk/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/helpdesk">> = Specific
  const handler = {} as typeof import("../../src/app/helpdesk/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/helpdesk/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/helpdesk/settings">> = Specific
  const handler = {} as typeof import("../../src/app/helpdesk/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/helpdesk/system-tickets/[ticketId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/helpdesk/system-tickets/[ticketId]">> = Specific
  const handler = {} as typeof import("../../src/app/helpdesk/system-tickets/[ticketId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/helpdesk/system-tickets/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/helpdesk/system-tickets/new">> = Specific
  const handler = {} as typeof import("../../src/app/helpdesk/system-tickets/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/helpdesk/system-tickets/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/helpdesk/system-tickets">> = Specific
  const handler = {} as typeof import("../../src/app/helpdesk/system-tickets/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/helpdesk/user-tickets/[ticketId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/helpdesk/user-tickets/[ticketId]">> = Specific
  const handler = {} as typeof import("../../src/app/helpdesk/user-tickets/[ticketId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/helpdesk/user-tickets/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/helpdesk/user-tickets">> = Specific
  const handler = {} as typeof import("../../src/app/helpdesk/user-tickets/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/login">> = Specific
  const handler = {} as typeof import("../../src/app/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/project-management/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/project-management">> = Specific
  const handler = {} as typeof import("../../src/app/project-management/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/servers/live/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/servers/live">> = Specific
  const handler = {} as typeof import("../../src/app/servers/live/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/servers/nextbidder/credentials/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/servers/nextbidder/credentials">> = Specific
  const handler = {} as typeof import("../../src/app/servers/nextbidder/credentials/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/servers/nextbidder/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/servers/nextbidder">> = Specific
  const handler = {} as typeof import("../../src/app/servers/nextbidder/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/servers/nexttask/credentials/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/servers/nexttask/credentials">> = Specific
  const handler = {} as typeof import("../../src/app/servers/nexttask/credentials/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/servers/nexttask/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/servers/nexttask">> = Specific
  const handler = {} as typeof import("../../src/app/servers/nexttask/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/servers/nexttech/credentials/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/servers/nexttech/credentials">> = Specific
  const handler = {} as typeof import("../../src/app/servers/nexttech/credentials/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/servers/nexttech/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/servers/nexttech">> = Specific
  const handler = {} as typeof import("../../src/app/servers/nexttech/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/servers/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/servers">> = Specific
  const handler = {} as typeof import("../../src/app/servers/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/servers/portals/credentials/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/servers/portals/credentials">> = Specific
  const handler = {} as typeof import("../../src/app/servers/portals/credentials/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/servers/portals/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/servers/portals">> = Specific
  const handler = {} as typeof import("../../src/app/servers/portals/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/servers/sources/credentials/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/servers/sources/credentials">> = Specific
  const handler = {} as typeof import("../../src/app/servers/sources/credentials/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/servers/sources/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/servers/sources">> = Specific
  const handler = {} as typeof import("../../src/app/servers/sources/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/servers/tradelines/[tradeline]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/servers/tradelines/[tradeline]">> = Specific
  const handler = {} as typeof import("../../src/app/servers/tradelines/[tradeline]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/servers/tradelines/credentials/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/servers/tradelines/credentials">> = Specific
  const handler = {} as typeof import("../../src/app/servers/tradelines/credentials/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/servers/tradelines/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/servers/tradelines">> = Specific
  const handler = {} as typeof import("../../src/app/servers/tradelines/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/session-logs/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/session-logs">> = Specific
  const handler = {} as typeof import("../../src/app/session-logs/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/settings/clients/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/settings/clients/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/settings/clients/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/settings/clients/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/settings/clients/new">> = Specific
  const handler = {} as typeof import("../../src/app/settings/clients/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/settings/clients/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/settings/clients">> = Specific
  const handler = {} as typeof import("../../src/app/settings/clients/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/settings">> = Specific
  const handler = {} as typeof import("../../src/app/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/settings/profile/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/settings/profile">> = Specific
  const handler = {} as typeof import("../../src/app/settings/profile/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/settings/timesheets/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/settings/timesheets">> = Specific
  const handler = {} as typeof import("../../src/app/settings/timesheets/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/studio/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/studio">> = Specific
  const handler = {} as typeof import("../../src/app/studio/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/team/members/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/team/members/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/team/members/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/team/members/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/team/members/new">> = Specific
  const handler = {} as typeof import("../../src/app/team/members/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/team/members/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/team/members">> = Specific
  const handler = {} as typeof import("../../src/app/team/members/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/team/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/team">> = Specific
  const handler = {} as typeof import("../../src/app/team/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/team/permissions/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/team/permissions">> = Specific
  const handler = {} as typeof import("../../src/app/team/permissions/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/team/reports/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/team/reports">> = Specific
  const handler = {} as typeof import("../../src/app/team/reports/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/team/roles/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/team/roles">> = Specific
  const handler = {} as typeof import("../../src/app/team/roles/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/the-forge/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/the-forge">> = Specific
  const handler = {} as typeof import("../../src/app/the-forge/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/tickets/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/tickets">> = Specific
  const handler = {} as typeof import("../../src/app/tickets/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/ai-team/api/control/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/ai-team/api/control">> = Specific
  const handler = {} as typeof import("../../src/app/ai-team/api/control/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/ai-team/api/status/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/ai-team/api/status">> = Specific
  const handler = {} as typeof import("../../src/app/ai-team/api/status/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/ai-team/api/usage/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/ai-team/api/usage">> = Specific
  const handler = {} as typeof import("../../src/app/ai-team/api/usage/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/ai-extractions/by-project/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ai-extractions/by-project">> = Specific
  const handler = {} as typeof import("../../src/app/api/ai-extractions/by-project/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/ai-extractions/clair/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ai-extractions/clair">> = Specific
  const handler = {} as typeof import("../../src/app/api/ai-extractions/clair/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/ai-extractions/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ai-extractions">> = Specific
  const handler = {} as typeof import("../../src/app/api/ai-extractions/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/ai-sessions/buckets/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ai-sessions/buckets">> = Specific
  const handler = {} as typeof import("../../src/app/api/ai-sessions/buckets/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/ai-sessions/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ai-sessions">> = Specific
  const handler = {} as typeof import("../../src/app/api/ai-sessions/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/clients/[id]/devs/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/clients/[id]/devs">> = Specific
  const handler = {} as typeof import("../../src/app/api/clients/[id]/devs/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/clients/[id]/projects/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/clients/[id]/projects">> = Specific
  const handler = {} as typeof import("../../src/app/api/clients/[id]/projects/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/clients/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/clients/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/clients/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/clients/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/clients">> = Specific
  const handler = {} as typeof import("../../src/app/api/clients/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/deploy/dev-environment/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/deploy/dev-environment">> = Specific
  const handler = {} as typeof import("../../src/app/api/deploy/dev-environment/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/dev-controls/analytics/debug/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/dev-controls/analytics/debug">> = Specific
  const handler = {} as typeof import("../../src/app/api/dev-controls/analytics/debug/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/dev-controls/analytics/engine/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/dev-controls/analytics/engine">> = Specific
  const handler = {} as typeof import("../../src/app/api/dev-controls/analytics/engine/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/dev-redirect/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/dev-redirect">> = Specific
  const handler = {} as typeof import("../../src/app/api/dev-redirect/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/dev-server/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/dev-server">> = Specific
  const handler = {} as typeof import("../../src/app/api/dev-server/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/dev-session/connect/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/dev-session/connect">> = Specific
  const handler = {} as typeof import("../../src/app/api/dev-session/connect/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/dev-session/disconnect/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/dev-session/disconnect">> = Specific
  const handler = {} as typeof import("../../src/app/api/dev-session/disconnect/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/dev-session/status/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/dev-session/status">> = Specific
  const handler = {} as typeof import("../../src/app/api/dev-session/status/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/engine-redirect/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/engine-redirect">> = Specific
  const handler = {} as typeof import("../../src/app/api/engine-redirect/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/engine/health/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/engine/health">> = Specific
  const handler = {} as typeof import("../../src/app/api/engine/health/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/nextbidder/worker/health/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/nextbidder/worker/health">> = Specific
  const handler = {} as typeof import("../../src/app/api/nextbidder/worker/health/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/patcher/[...path]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/patcher/[...path]">> = Specific
  const handler = {} as typeof import("../../src/app/api/patcher/[...path]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/portals/worker/health/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/portals/worker/health">> = Specific
  const handler = {} as typeof import("../../src/app/api/portals/worker/health/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/server/[action]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/server/[action]">> = Specific
  const handler = {} as typeof import("../../src/app/api/server/[action]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/servers/health/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/servers/health">> = Specific
  const handler = {} as typeof import("../../src/app/api/servers/health/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/servers/logs/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/servers/logs">> = Specific
  const handler = {} as typeof import("../../src/app/api/servers/logs/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/servers/reboot/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/servers/reboot">> = Specific
  const handler = {} as typeof import("../../src/app/api/servers/reboot/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/sources/worker/health/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/sources/worker/health">> = Specific
  const handler = {} as typeof import("../../src/app/api/sources/worker/health/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/susan/[...path]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/susan/[...path]">> = Specific
  const handler = {} as typeof import("../../src/app/api/susan/[...path]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/susan/chat/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/susan/chat">> = Specific
  const handler = {} as typeof import("../../src/app/api/susan/chat/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/susan/conflicts/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/susan/conflicts">> = Specific
  const handler = {} as typeof import("../../src/app/api/susan/conflicts/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/susan/notifications/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/susan/notifications">> = Specific
  const handler = {} as typeof import("../../src/app/api/susan/notifications/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/team/members/[id]/deactivate/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/team/members/[id]/deactivate">> = Specific
  const handler = {} as typeof import("../../src/app/api/team/members/[id]/deactivate/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/team/members/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/team/members/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/team/members/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/team/members/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/team/members">> = Specific
  const handler = {} as typeof import("../../src/app/api/team/members/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/team/permissions/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/team/permissions">> = Specific
  const handler = {} as typeof import("../../src/app/api/team/permissions/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/team/roles/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/team/roles">> = Specific
  const handler = {} as typeof import("../../src/app/api/team/roles/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/team/stats/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/team/stats">> = Specific
  const handler = {} as typeof import("../../src/app/api/team/stats/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/tradelines/[action]/[tradeline]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/tradelines/[action]/[tradeline]">> = Specific
  const handler = {} as typeof import("../../src/app/api/tradelines/[action]/[tradeline]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/tradelines/[action]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/tradelines/[action]">> = Specific
  const handler = {} as typeof import("../../src/app/api/tradelines/[action]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/tradelines/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/tradelines">> = Specific
  const handler = {} as typeof import("../../src/app/api/tradelines/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/tradelines/stats/[tradeline]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/tradelines/stats/[tradeline]">> = Specific
  const handler = {} as typeof import("../../src/app/api/tradelines/stats/[tradeline]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/tradelines/worker/health/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/tradelines/worker/health">> = Specific
  const handler = {} as typeof import("../../src/app/api/tradelines/worker/health/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/users/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/users">> = Specific
  const handler = {} as typeof import("../../src/app/api/users/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/project-management/api/clair/[...path]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/project-management/api/clair/[...path]">> = Specific
  const handler = {} as typeof import("../../src/app/project-management/api/clair/[...path]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/project-management/api/clients/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/project-management/api/clients">> = Specific
  const handler = {} as typeof import("../../src/app/project-management/api/clients/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/project-management/api/conventions/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/project-management/api/conventions/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/project-management/api/conventions/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/project-management/api/conventions/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/project-management/api/conventions">> = Specific
  const handler = {} as typeof import("../../src/app/project-management/api/conventions/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/project-management/api/phases/[projectId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/project-management/api/phases/[projectId]">> = Specific
  const handler = {} as typeof import("../../src/app/project-management/api/phases/[projectId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/project-management/api/pipeline/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/project-management/api/pipeline">> = Specific
  const handler = {} as typeof import("../../src/app/project-management/api/pipeline/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/project-management/api/project-docs/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/project-management/api/project-docs">> = Specific
  const handler = {} as typeof import("../../src/app/project-management/api/project-docs/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/project-management/api/project-knowledge/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/project-management/api/project-knowledge">> = Specific
  const handler = {} as typeof import("../../src/app/project-management/api/project-knowledge/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/project-management/api/project-paths/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/project-management/api/project-paths">> = Specific
  const handler = {} as typeof import("../../src/app/project-management/api/project-paths/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/project-management/api/projects/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/project-management/api/projects/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/project-management/api/projects/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/project-management/api/projects/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/project-management/api/projects">> = Specific
  const handler = {} as typeof import("../../src/app/project-management/api/projects/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/project-management/api/projects/summary/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/project-management/api/projects/summary">> = Specific
  const handler = {} as typeof import("../../src/app/project-management/api/projects/summary/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/the-forge/the-forge/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/the-forge/the-forge">> = Specific
  const handler = {} as typeof import("../../src/app/the-forge/the-forge/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../src/app/credentials/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/credentials">> = Specific
  const handler = {} as typeof import("../../src/app/credentials/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
