var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/calendar/time-clock/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__443ca4ea._.js")
R.c("server/chunks/ssr/7c33f_next_dist_808c96d2._.js")
R.c("server/chunks/ssr/Studio_kodiack-dashboard-5500_2ce3ec92._.js")
R.c("server/chunks/ssr/[root-of-the-server]__daab2a21._.js")
R.c("server/chunks/ssr/[root-of-the-server]__6055a7a4._.js")
R.c("server/chunks/ssr/7c33f_next_dist_b71a5a34._.js")
R.c("server/chunks/ssr/7c33f_next_dist_client_components_builtin_global-error_b47b8e1e.js")
R.c("server/chunks/ssr/Studio_kodiack-dashboard-5500_src_app_layout_tsx_3024de76._.js")
R.c("server/chunks/ssr/7c33f_next_dist_client_components_fba8f4ce._.js")
R.c("server/chunks/ssr/7c33f_next_dist_client_components_builtin_forbidden_dae5c044.js")
R.c("server/chunks/ssr/7c33f_next_dist_client_components_builtin_unauthorized_69ca8b14.js")
R.c("server/chunks/ssr/Studio_kodiack-dashboard-5500_src_app_calendar_loading_tsx_38eaeb44._.js")
R.c("server/chunks/ssr/d1936__next-internal_server_app_calendar_time-clock_page_actions_f66edfcd.js")
R.m(40518)
module.exports=R.m(40518).exports
