module.exports = [
"[project]/Studio/kodiack-dashboard-5500/src/app/layout.tsx [app-rsc] (client reference proxy) <module evaluation>", ((__turbopack_context__) => {
"use strict";

// This file is generated by next-core EcmascriptClientReferenceModule.
__turbopack_context__.s([
    "PageActionsContext",
    ()=>PageActionsContext,
    "PageTitleContext",
    ()=>PageTitleContext,
    "ProductionStatusContext",
    ()=>ProductionStatusContext,
    "default",
    ()=>__TURBOPACK__default__export__
]);
var __TURBOPACK__imported__module__$5b$project$5d2f$Studio$2f$kodiack$2d$dashboard$2d$5500$2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$server$2d$dom$2d$turbopack$2d$server$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/Studio/kodiack-dashboard-5500/node_modules/next/dist/server/route-modules/app-page/vendored/rsc/react-server-dom-turbopack-server.js [app-rsc] (ecmascript)");
;
const PageActionsContext = (0, __TURBOPACK__imported__module__$5b$project$5d2f$Studio$2f$kodiack$2d$dashboard$2d$5500$2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$server$2d$dom$2d$turbopack$2d$server$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["registerClientReference"])(function() {
    throw new Error("Attempted to call PageActionsContext() from the server but PageActionsContext is on the client. It's not possible to invoke a client function from the server, it can only be rendered as a Component or passed to props of a Client Component.");
}, "[project]/Studio/kodiack-dashboard-5500/src/app/layout.tsx <module evaluation>", "PageActionsContext");
const PageTitleContext = (0, __TURBOPACK__imported__module__$5b$project$5d2f$Studio$2f$kodiack$2d$dashboard$2d$5500$2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$server$2d$dom$2d$turbopack$2d$server$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["registerClientReference"])(function() {
    throw new Error("Attempted to call PageTitleContext() from the server but PageTitleContext is on the client. It's not possible to invoke a client function from the server, it can only be rendered as a Component or passed to props of a Client Component.");
}, "[project]/Studio/kodiack-dashboard-5500/src/app/layout.tsx <module evaluation>", "PageTitleContext");
const ProductionStatusContext = (0, __TURBOPACK__imported__module__$5b$project$5d2f$Studio$2f$kodiack$2d$dashboard$2d$5500$2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$server$2d$dom$2d$turbopack$2d$server$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["registerClientReference"])(function() {
    throw new Error("Attempted to call ProductionStatusContext() from the server but ProductionStatusContext is on the client. It's not possible to invoke a client function from the server, it can only be rendered as a Component or passed to props of a Client Component.");
}, "[project]/Studio/kodiack-dashboard-5500/src/app/layout.tsx <module evaluation>", "ProductionStatusContext");
const __TURBOPACK__default__export__ = (0, __TURBOPACK__imported__module__$5b$project$5d2f$Studio$2f$kodiack$2d$dashboard$2d$5500$2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$server$2d$dom$2d$turbopack$2d$server$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["registerClientReference"])(function() {
    throw new Error("Attempted to call the default export of [project]/Studio/kodiack-dashboard-5500/src/app/layout.tsx <module evaluation> from the server, but it's on the client. It's not possible to invoke a client function from the server, it can only be rendered as a Component or passed to props of a Client Component.");
}, "[project]/Studio/kodiack-dashboard-5500/src/app/layout.tsx <module evaluation>", "default");
}),
"[project]/Studio/kodiack-dashboard-5500/src/app/layout.tsx [app-rsc] (client reference proxy)", ((__turbopack_context__) => {
"use strict";

// This file is generated by next-core EcmascriptClientReferenceModule.
__turbopack_context__.s([
    "PageActionsContext",
    ()=>PageActionsContext,
    "PageTitleContext",
    ()=>PageTitleContext,
    "ProductionStatusContext",
    ()=>ProductionStatusContext,
    "default",
    ()=>__TURBOPACK__default__export__
]);
var __TURBOPACK__imported__module__$5b$project$5d2f$Studio$2f$kodiack$2d$dashboard$2d$5500$2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$server$2d$dom$2d$turbopack$2d$server$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/Studio/kodiack-dashboard-5500/node_modules/next/dist/server/route-modules/app-page/vendored/rsc/react-server-dom-turbopack-server.js [app-rsc] (ecmascript)");
;
const PageActionsContext = (0, __TURBOPACK__imported__module__$5b$project$5d2f$Studio$2f$kodiack$2d$dashboard$2d$5500$2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$server$2d$dom$2d$turbopack$2d$server$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["registerClientReference"])(function() {
    throw new Error("Attempted to call PageActionsContext() from the server but PageActionsContext is on the client. It's not possible to invoke a client function from the server, it can only be rendered as a Component or passed to props of a Client Component.");
}, "[project]/Studio/kodiack-dashboard-5500/src/app/layout.tsx", "PageActionsContext");
const PageTitleContext = (0, __TURBOPACK__imported__module__$5b$project$5d2f$Studio$2f$kodiack$2d$dashboard$2d$5500$2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$server$2d$dom$2d$turbopack$2d$server$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["registerClientReference"])(function() {
    throw new Error("Attempted to call PageTitleContext() from the server but PageTitleContext is on the client. It's not possible to invoke a client function from the server, it can only be rendered as a Component or passed to props of a Client Component.");
}, "[project]/Studio/kodiack-dashboard-5500/src/app/layout.tsx", "PageTitleContext");
const ProductionStatusContext = (0, __TURBOPACK__imported__module__$5b$project$5d2f$Studio$2f$kodiack$2d$dashboard$2d$5500$2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$server$2d$dom$2d$turbopack$2d$server$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["registerClientReference"])(function() {
    throw new Error("Attempted to call ProductionStatusContext() from the server but ProductionStatusContext is on the client. It's not possible to invoke a client function from the server, it can only be rendered as a Component or passed to props of a Client Component.");
}, "[project]/Studio/kodiack-dashboard-5500/src/app/layout.tsx", "ProductionStatusContext");
const __TURBOPACK__default__export__ = (0, __TURBOPACK__imported__module__$5b$project$5d2f$Studio$2f$kodiack$2d$dashboard$2d$5500$2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$server$2d$dom$2d$turbopack$2d$server$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["registerClientReference"])(function() {
    throw new Error("Attempted to call the default export of [project]/Studio/kodiack-dashboard-5500/src/app/layout.tsx from the server, but it's on the client. It's not possible to invoke a client function from the server, it can only be rendered as a Component or passed to props of a Client Component.");
}, "[project]/Studio/kodiack-dashboard-5500/src/app/layout.tsx", "default");
}),
"[project]/Studio/kodiack-dashboard-5500/src/app/layout.tsx [app-rsc] (ecmascript)", ((__turbopack_context__) => {
"use strict";

var __TURBOPACK__imported__module__$5b$project$5d2f$Studio$2f$kodiack$2d$dashboard$2d$5500$2f$src$2f$app$2f$layout$2e$tsx__$5b$app$2d$rsc$5d$__$28$client__reference__proxy$29$__$3c$module__evaluation$3e$__ = __turbopack_context__.i("[project]/Studio/kodiack-dashboard-5500/src/app/layout.tsx [app-rsc] (client reference proxy) <module evaluation>");
var __TURBOPACK__imported__module__$5b$project$5d2f$Studio$2f$kodiack$2d$dashboard$2d$5500$2f$src$2f$app$2f$layout$2e$tsx__$5b$app$2d$rsc$5d$__$28$client__reference__proxy$29$__ = __turbopack_context__.i("[project]/Studio/kodiack-dashboard-5500/src/app/layout.tsx [app-rsc] (client reference proxy)");
;
__turbopack_context__.n(__TURBOPACK__imported__module__$5b$project$5d2f$Studio$2f$kodiack$2d$dashboard$2d$5500$2f$src$2f$app$2f$layout$2e$tsx__$5b$app$2d$rsc$5d$__$28$client__reference__proxy$29$__);
}),
];

//# sourceMappingURL=Studio_kodiack-dashboard-5500_src_app_layout_tsx_3024de76._.js.map