var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/studio/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__b0d95550._.js")
R.c("server/chunks/ssr/7c33f_next_dist_808c96d2._.js")
R.c("server/chunks/ssr/Studio_kodiack-dashboard-5500_aa3cc967._.js")
R.c("server/chunks/ssr/[root-of-the-server]__daab2a21._.js")
R.c("server/chunks/ssr/[root-of-the-server]__6055a7a4._.js")
R.c("server/chunks/ssr/7c33f_next_dist_b71a5a34._.js")
R.c("server/chunks/ssr/7c33f_next_dist_client_components_builtin_global-error_b47b8e1e.js")
R.c("server/chunks/ssr/Studio_kodiack-dashboard-5500_src_app_layout_tsx_3024de76._.js")
R.c("server/chunks/ssr/7c33f_next_dist_client_components_fba8f4ce._.js")
R.c("server/chunks/ssr/7c33f_next_dist_client_components_builtin_forbidden_dae5c044.js")
R.c("server/chunks/ssr/7c33f_next_dist_client_components_builtin_unauthorized_69ca8b14.js")
R.c("server/chunks/ssr/eb22a_kodiack-dashboard-5500__next-internal_server_app_studio_page_actions_f2a79731.js")
R.m(24570)
module.exports=R.m(24570).exports
